language: php

php:
  - hhvm

env:
  - ADAPTER=MemoryStore

services:
  - memcached
  - redis

before_script:
  - tests/.travis/$ADAPTER.sh
  - composer self-update && composer install --dev

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true

sudo: required
