language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

sudo: required

env:
  - ADAPTER=PostgreSQL

services:
  - docker

before_script:
  - tests/.travis/$ADAPTER.sh
  - composer self-update && composer install --dev

script:
  - ./vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
      env: ADAPTER=Apc
    - php: 7.0
      env: ADAPTER=Memcached
    - php: 7.0
      env: ADAPTER=Redis
    - php: 7.0
      env: ADAPTER=Couchbase
    - php: hhvm
      env: ADAPTER=Couchbase
    - php: hhvm
      env: ADAPTER=PostgreSQL
