language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

env:
  - ADAPTER=MemoryStore
  - ADAPTER=Apc
  - ADAPTER=Memcached
  - ADAPTER=Redis
  - ADAPTER=Couchbase
  - ADAPTER=MySQL
  - ADAPTER=SQLite
  - ADAPTER=PostgreSQL
  - ADAPTER=Filesystem
  - ADAPTER=Flysystem

services:
  - docker
  - redis

before_script:
  - tests/.travis/$ADAPTER.sh
  - composer self-update && composer install --dev

script:
  - ./vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
      env: ADAPTER=Apc
    - php: 7.0
      env: ADAPTER=Memcached
    - php: 7.0
      env: ADAPTER=Redis
    - php: 7.0
      env: ADAPTER=Couchbase
    - php: hhvm
      env: ADAPTER=Couchbase
    - php: hhvm
      env: ADAPTER=PostgreSQL

sudo: required
