language: php

php:
  - 7.1
  - 7.0
  - 5.6

env:
  - ADAPTER=MemoryStore
  - ADAPTER=Apc
  - ADAPTER=Memcached
  - ADAPTER=Redis
  - ADAPTER=Couchbase
  - ADAPTER=MySQL
  - ADAPTER=SQLite
  - ADAPTER=PostgreSQL
  - ADAPTER=Flysystem

services:
  - docker

script:
  - make test PHP=$(phpenv version-name) ADAPTER=$(ADAPTER)

matrix:
  fast_finish: true
