sudo: required

language: php

php:
  - 7.1
  - 7.0
  - 5.6

env:
  - ADAPTER=MemoryStore
  - ADAPTER=Apc
  - ADAPTER=Memcached
  - ADAPTER=Redis
  - ADAPTER=Couchbase
  - ADAPTER=MySQL
  - ADAPTER=SQLite
  - ADAPTER=PostgreSQL
  - ADAPTER=Flysystem

services:
  - docker

before_install:
  # need at least version 17.05, for ARG support in FROM
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - make up PHP=$(phpenv version-name) ADAPTER=${ADAPTER}
  # give services some time to be fully up & running
  - sleep 60

script:
  - make test PHP=$(phpenv version-name) ADAPTER=${ADAPTER} UP=0 DOWN=0

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - make down PHP=$(phpenv version-name) ADAPTER=${ADAPTER}

matrix:
  fast_finish: true
