language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

sudo: required

env:
  - ADAPTER=MemoryStore
  - ADAPTER=Apc
  - ADAPTER=Memcached
  - ADAPTER=Redis
  - ADAPTER=Couchbase
  - ADAPTER=MySQL
  - ADAPTER=SQLite
  - ADAPTER=PostgreSQL
  - ADAPTER=Flysystem

services:
  - docker

before_script:
  - pip install --user codecov
  - tests/.travis/$ADAPTER.sh
  - composer self-update && composer install --dev

script:
  - ./vendor/bin/phpunit --group "${ADAPTER}"

after_success:
  - codecov

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
      env: ADAPTER=Memcached
    - php: 7.0
      env: ADAPTER=Redis
    - php: 7.0
      env: ADAPTER=Couchbase
    - php: hhvm
      env: ADAPTER=Apc
    - php: hhvm
      env: ADAPTER=Redis
    - php: hhvm
      env: ADAPTER=Couchbase
    # These currently fail to compile PECL packages for the correct PHP version
    # @see https://github.com/travis-ci/travis-ci/issues/6490
    - php: 5.4
    - php: 5.6
