# Setup
title:            Scrapbook
description:      'Scrapbook is a caching environment for PHP, with adapters for e.g. Memcached, Redis, Couchbase, APC(u), SQL and additional capabilities (e.g. transactions) built on top.'
url:              http://www.scrapbook.cash
baseurl:          /
image:            public/logo.png

author:
  name:           'Matthias Mullie'
  gplus:          https://plus.google.com/u/0/114103174273569238978
  twitter:        matthiasmullie

twitter:          scrapbook_cache

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/matthiasmullie/scrapbook

permalink:        /:title/

gems:
  # Generate sitemap
  - jekyll-sitemap
