version: '2.1'
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
    environment:
      - couchbase-host=couchbase
      - couchbase-port=11210
      - memcached-host=memcached
      - memcached-port=11211
      - mysql-host=mysql
      - mysql-port=3306
      - postgresql-host=postgresql
      - postgresql-port=5432
      - redis-host=redis
      - redis-port=6379
  '7.1':
    extends: php
    build:
      context: .
      dockerfile: docker/Dockerfile-7.1
  '7.0':
    extends: php
    build:
      context: .
      dockerfile: docker/Dockerfile-7.0
  '5.6':
    extends: php
    build:
      context: .
      dockerfile: docker/Dockerfile-5.6
  memcached:
    image: memcached
  couchbase:
    build:
      context: .
      dockerfile: docker/Dockerfile-Couchbase
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=cache
  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=cache
  redis:
    image: redis
