name: healthcheck

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - name: Test (twice, if needed)
        run: make test || make test
      - name: Healthcheck ping
        run: wget https://healthchecks.home.mullie.eu/ping/b4f2ebd8-b9e7-44db-8a9c-b1f796a3f86c -T 10 -t 5 -O /dev/null
