name: test-suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test PHP 8.2
        run: make test PHP=8.2
      - name: Test PHP 8.1
        run: make test PHP=8.1
      - name: Test PHP 8.0
        run: make test PHP=8.0
      - uses: codecov/codecov-action@v3
        with:
          directory: build
